name: Render PlantUML & Release

on:
  push:
    branches: [ "master" ]
    paths:
      - "diagrams/**/*.puml"
      - "diagrams/*.puml"
      - "includes/**/*.puml"
      - "includes/*.puml"
      - "Makefile"

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PlantUML & deps
        run: sudo apt-get install -y plantuml make

      - name: Render diagrams using make
        run: make

      - name: Package diagrams into ZIP
        run: |
          mkdir -p release
          zip -r release/rendered-diagrams.zip build/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
