name: Render PlantUML & Release

on:
  push:
    branches: [ "master" ]
    paths:
      - "diagrams/**/*.puml"
      - "diagrams/*.puml"
      - "includes/**/*.puml"
      - "includes/*.puml"
      - "Makefile"

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install PlantUML & deps
        run: sudo apt-get update && sudo apt-get install -y plantuml make

      - name: Render diagrams using make
        run: make

      - name: Create tag
        run: |
          TAG="v$(date +'%Y%m%d-%H%M%S')"
          echo "TAG=$TAG" >> $GITHUB_ENV
          git tag $TAG
          git push origin $TAG

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: build/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
